name: betting_tips
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  fluttertoast: any
  colorful_safe_area: any
  sprintf: any
  provider: any
  in_app_purchase: any
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: any

flutter_native_splash:
  color: '#ffffff'
  image: assets/logo.png
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf